# Generated by Django 3.2.9 on 2021-11-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=100)),
                ('song_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('Like_Count', models.CharField(max_length=50)),
                ('Lyric', models.CharField(max_length=500)),
                ('cover_url', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
                'db_table': 'tb_song',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=100)),
                ('tag_name', models.CharField(max_length=100)),
                ('variable_id', models.CharField(max_length=100)),
                ('variable_name', models.CharField(max_length=100)),
                ('variable_name_en', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'db_table': 'tb_tag',
            },
        ),
    ]
