# Generated by Django 3.2.9 on 2021-11-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=100)),
                ('song_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('Like_Count', models.CharField(max_length=50)),
                ('Lyric', models.CharField(max_length=500)),
                ('cover_url', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
                'db_table': 'tb_song',
            },
        ),
    ]
