# Generated by Django 3.2.9 on 2021-12-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('freq', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'top11',
                'db_table': 'tb_top11',
            },
        ),
        migrations.CreateModel(
            name='Top11_like100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('freq', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'top11_like100',
                'db_table': 'tb_top11_like100',
            },
        ),
    ]
