# Generated by Django 3.2.9 on 2021-11-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
