module.exports = {
    categories: ['트렌드/연도', '뮤직 스타일', '계절/시간/날씨', '상황/장소', '감정/기분'],
    data: [
        {
            url: 'http://127.0.0.1:8000/api/tags/0/',
            category_id: '0',
            category_name: '트렌드/연도',
            tag_id: '0_1',
            tag_name: '트렌드',
            tag_name_en: 'trend',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/0/',
            category_id: '0',
            category_name: '트렌드/연도',
            tag_id: '0_2',
            tag_name: '1940년대',
            tag_name_en: '1940s',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/0/',
            category_id: '0',
            category_name: '트렌드/연도',
            tag_id: '0_3',
            tag_name: '1950년대',
            tag_name_en: '1950s',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/0/',
            category_id: '0',
            category_name: '트렌드/연도',
            tag_id: '0_4',
            tag_name: '1960년대',
            tag_name_en: '1960s',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/0/',
            category_id: '0',
            category_name: '트렌드/연도',
            tag_id: '0_5',
            tag_name: '1970년대',
            tag_name_en: '1960s',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/0/',
            category_id: '0',
            category_name: '트렌드/연도',
            tag_id: '0_6',
            tag_name: '1980년대',
            tag_name_en: '1960s',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/0/',
            category_id: '0',
            category_name: '트렌드/연도',
            tag_id: '0_7',
            tag_name: '1990년대',
            tag_name_en: '1960s',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/0/',
            category_id: '0',
            category_name: '트렌드/연도',
            tag_id: '0_8',
            tag_name: '2000년대',
            tag_name_en: '1950s',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/0/',
            category_id: '0',
            category_name: '트렌드/연도',
            tag_id: '0_9',
            tag_name: '2010년대',
            tag_name_en: '2010s',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/0/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '0',
            tag_name: '신나는',
            tag_name_en: 'exciting',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/2/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '2',
            tag_name: '그루브한',
            tag_name_en: 'grooved',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/3/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '3',
            tag_name: '감성적인',
            tag_name_en: 'emotional',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/4/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '4',
            tag_name: '어쿠스틱한',
            tag_name_en: 'acoustic',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/5/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '5',
            tag_name: '일렉트로닉',
            tag_name_en: 'electronic',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/6/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '6',
            tag_name: '달달한',
            tag_name_en: 'sweet',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/7/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '7',
            tag_name: '몽환적인',
            tag_name_en: 'dreamy',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/8/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '8',
            tag_name: '강한',
            tag_name_en: 'strong',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/9/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '9',
            tag_name: '잔잔한',
            tag_name_en: 'windless',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/10/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '10',
            tag_name: '올디스',
            tag_name_en: 'oldies',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/11/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '11',
            tag_name: '애절한',
            tag_name_en: 'sad',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/12/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '12',
            tag_name: '감각적인',
            tag_name_en: 'sensual',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/13/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '13',
            tag_name: '섹시한',
            tag_name_en: 'sexy',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/14/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '14',
            tag_name: '쓸쓸한',
            tag_name_en: 'lonesome',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/15/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '15',
            tag_name: '소울풀한',
            tag_name_en: 'soulful',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/16/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '16',
            tag_name: '청량한',
            tag_name_en: 'refreshing',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/17/',
            category_id: '2',
            category_name: '계절/시간/날씨',
            tag_id: '17',
            tag_name: '봄',
            tag_name_en: 'spring',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/19/',
            category_id: '2',
            category_name: '계절/시간/날씨',
            tag_id: '19',
            tag_name: '가을',
            tag_name_en: 'autumn',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/18/',
            category_id: '2',
            category_name: '계절/시간/날씨',
            tag_id: '18',
            tag_name: '여름',
            tag_name_en: 'summer',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/20/',
            category_id: '2',
            category_name: '계절/시간/날씨',
            tag_id: '20',
            tag_name: '겨울',
            tag_name_en: 'winter',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/22/',
            category_id: '3',
            category_name: '계절/시간/날씨',
            tag_id: '22',
            tag_name: '오후',
            tag_name_en: 'afternoon',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/21/',
            category_id: '3',
            category_name: '계절/시간/날씨',
            tag_id: '21',
            tag_name: '아침',
            tag_name_en: 'morning',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/23/',
            category_id: '3',
            category_name: '계절/시간/날씨',
            tag_id: '23',
            tag_name: '저녁',
            tag_name_en: 'dinner',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/1/',
            category_id: '1',
            category_name: '뮤직 스타일',
            tag_id: '1',
            tag_name: '발라드한',
            tag_name_en: 'ballad',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/24/',
            category_id: '3',
            category_name: '계절/시간/날씨',
            tag_id: '24',
            tag_name: '밤/새벽',
            tag_name_en: 'night_dawn',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/25/',
            category_id: '4',
            category_name: '계절/시간/날씨',
            tag_id: '25',
            tag_name: '화창한 날',
            tag_name_en: 'sunny',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/26/',
            category_id: '4',
            category_name: '계절/시간/날씨',
            tag_id: '26',
            tag_name: '비/흐림',
            tag_name_en: 'rain_cloudy',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/27/',
            category_id: '4',
            category_name: '계절/시간/날씨',
            tag_id: '27',
            tag_name: '눈오는 날',
            tag_name_en: 'snowy',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/28/',
            category_id: '4',
            category_name: '계절/시간/날씨',
            tag_id: '28',
            tag_name: '비온후/맑게갠',
            tag_name_en: 'after_rain_clear',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/29/',
            category_id: '4',
            category_name: '계절/시간/날씨',
            tag_id: '29',
            tag_name: '선선한',
            tag_name_en: 'cool',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/30/',
            category_id: '4',
            category_name: '계절/시간/날씨',
            tag_id: '30',
            tag_name: '쌀쌀한',
            tag_name_en: 'chilly',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/31/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '31',
            tag_name: '드라이브',
            tag_name_en: 'drive',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/32/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '32',
            tag_name: '운동/헬스',
            tag_name_en: 'exercise_health',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/33/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '33',
            tag_name: '등교/출근길',
            tag_name_en: 'on_the_way_to_school',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/34/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '34',
            tag_name: '하교/퇴근길',
            tag_name_en: 'on_the_way_home',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/35/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '35',
            tag_name: '휴식/명상',
            tag_name_en: 'relaxation_meditation',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/36/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '36',
            tag_name: '클럽/파티',
            tag_name_en: 'club_party',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/37/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '37',
            tag_name: '카페',
            tag_name_en: 'cafe',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/38/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '38',
            tag_name: '노래방',
            tag_name_en: 'karaoke',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/40/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '40',
            tag_name: '사무실',
            tag_name_en: 'walk_trip',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/41/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '41',
            tag_name: '편집숍/매장',
            tag_name_en: 'office',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/42/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '42',
            tag_name: '독서방안에서',
            tag_name_en: 'select_shop_store',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/39/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '39',
            tag_name: '산책/여행',
            tag_name_en: 'in_the_reading_room',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/43/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '43',
            tag_name: '호텔/바',
            tag_name_en: 'hotel_bar',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/44/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '44',
            tag_name: '잠들기전',
            tag_name_en: 'before_sleeping',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/45/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '45',
            tag_name: '결혼',
            tag_name_en: 'marriage',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/47/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '47',
            tag_name: '패션쇼',
            tag_name_en: 'fashion_show',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/46/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '46',
            tag_name: '페스티벌',
            tag_name_en: 'festival',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/48/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '48',
            tag_name: '혼술혼밥',
            tag_name_en: 'eat_alone',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/49/',
            category_id: '5',
            category_name: '상황/장소',
            tag_id: '49',
            tag_name: '공부할때',
            tag_name_en: 'when_studying',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/50/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '50',
            tag_name: '사랑/기쁨',
            tag_name_en: 'love_joy',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/51/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '51',
            tag_name: '이별/슬픔',
            tag_name_en: 'farewell_sad',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/53/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '53',
            tag_name: '우울할때',
            tag_name_en: 'when_depressed',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/52/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '52',
            tag_name: '스트레스/짜증',
            tag_name_en: 'stress_irritability',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/54/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '54',
            tag_name: '지치고힘들때',
            tag_name_en: 'when_you_are_tired',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/55/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '55',
            tag_name: '멘붕/불안',
            tag_name_en: 'mental_anxiety',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/56/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '56',
            tag_name: '그리움',
            tag_name_en: 'longing',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/57/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '57',
            tag_name: '외로울때',
            tag_name_en: 'when_youre_lonely',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/58/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '58',
            tag_name: '썸탈때',
            tag_name_en: 'something',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/60/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '60',
            tag_name: '울고싶을때',
            tag_name_en: 'when_you_want_to_cry',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/61/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '61',
            tag_name: '새벽감성',
            tag_name_en: 'dawn',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/63/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '63',
            tag_name: '설렘/심쿵',
            tag_name_en: 'excitement_heart',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/64/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '64',
            tag_name: '기분전환',
            tag_name_en: 'diversion',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/59/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '59',
            tag_name: '고백',
            tag_name_en: 'ask_out',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/62/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '62',
            tag_name: '싱숭생숭',
            tag_name_en: 'bubbly',
        },
        {
            url: 'http://127.0.0.1:8000/api/tags/65/',
            category_id: '6',
            category_name: '감정/기분',
            tag_id: '65',
            tag_name: '힐링',
            tag_name_en: 'healing',
        },
    ],
};
