# Generated by Django 3.2.9 on 2021-11-22 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='confession',
            new_name='ask_out',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='something',
        ),
    ]
