# Generated by Django 3.2.9 on 2021-11-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_song_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation_result',
            name='result_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recommendation_result',
            name='survey_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='survey_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
